## Text Representation and Classification Project Overview

This project focuses on offensive language detection in social media posts. 

The following reference links were useful in this project

• [OffensEval Shared Task link](https://sites.google.com/site/offensevalsharedtask/)

• [Scikit Learn Documentation](https://scikit-learn.org/stable/)

• [TfidVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer)

• [Logistic Regression Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

• [Limited-memory BFGS Documentation](https://en.wikipedia.org/wiki/Limited-memory_BFGS)

• [SGDClassifier Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html)

• [ColumnTransformer Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html)

• [OneHotEncoder Documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)


## Dataset

The dataset used is from the OffensEval shared task, which contains tweets annotated for offensive language detection which is uploaded in this repo. The dataset includes:

* 13,240 tweets for training
* 860 tweets for testing
* Labels for SubTask A: offensive or non-offensive (binary classification)
* Labels for SubTask B: targeted, untargeted, or non-offensive (multiclass classification)
* Sentiment analysis annotations for each tweet

---

## Workflow

### Text Representation

Tweets were converted into numerical feature vectors using a bag-of-words model based on TF-IDF. The `TfidfVectorizer` from scikit-learn was used with default parameters, providing tokenization, stop-word handling, and other preprocessing. Feature vectors were generated by fitting the vectorizer on the training set and transforming both training and test sets, producing vectors with 19,083 dimensions.

### Classification Model

A `LogisticRegression` model was used to classify tweets:

* The model automatically adapted to binary or multiclass classification based on training labels.
* Default parameters were used, with the maximum number of training iterations increased to 1000 to ensure convergence.
* Predictions were made for both SubTask A and SubTask B.

### Model Evaluation

Model performance was assessed using appropriate metrics:

* SubTask A: accuracy and binary F1 score
* SubTask B: micro F1 and macro F1 score

Initial results indicated class imbalance in the dataset, with performance metrics reflecting the skewed distribution of labels.

### Handling Class Imbalance

A balanced version of `LogisticRegression` was created by automatically adjusting class weights. This reduced disparities between accuracy and F1 scores, and improved performance on minority classes in both subtasks.

### Additional Features

Sentiment annotations were incorporated as additional features using a `ColumnTransformer`:

* `TfidfVectorizer` applied to tweet text
* `OneHotEncoder` applied to sentiment labels

The resulting combined feature vectors increased in size to 19,086 dimensions, enhancing the model’s input with sentiment information.

---

## Technologies and Libraries

* Python 3.x
* pandas
* scikit-learn

---

## Key Functions

* `create_tfidfvectorizer()`: Returns a TF-IDF vectorizer with default parameters.
* `run_vectorizer(vectorizer, train_data, test_data)`: Fits and transforms the data using the vectorizer.
* `create_model()`: Creates a Logistic Regression model with default parameters and increased iterations.
* `run_model(model, X_train, y_train, X_test)`: Trains the model and generates predictions.
* `create_balanced_model()`: Creates a Logistic Regression model with automatic class weight adjustment.
* `create_column_transformer()`: Returns a ColumnTransformer combining TF-IDF text vectors and one-hot encoded sentiment features.

---

## Outcomes

* Tweets were successfully represented as high-dimensional numerical vectors.
* Logistic Regression models were trained and evaluated for binary and multiclass classification.
* Class imbalance was addressed through weighted modeling.
* Sentiment features were incorporated to improve model input and classification performance.

